<?php

/**************************************************************
 * Extension Manager/Repository config file for ext: "events"
 *
 * Auto generated by Extension Builder 2019-04-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Events',
    'description' => 'Extension to manage events',
    'category' => 'plugin',
    'author' => 'Dirk Koritnik',
    'author_email' => 'koritnik@werkraum-media.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
