<?php

declare(strict_types=1);

return  [
    'tx_events_domain_model_organizer' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'name' => 'Schillerhaus Rudolstadt',
            'street' => 'Schillerstraße 25',
            'district' => '',
            'city' => 'Rudolstadt',
            'zip' => '07407',
            'phone' => '+ 49 3672 / 486470',
            'web' => 'http://schillerhaus.rudolstadt.de',
            'email' => 'schillerhaus@rudolstadt.de',
        ],
        1 => [
            'uid' => '2',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'name' => 'Stadtbibliothek Rudolstadt',
            'street' => 'Schulplatz 13',
            'district' => '',
            'city' => 'Rudolstadt',
            'zip' => '07407',
            'phone' => '0 36 72 - 48 64 20',
            'web' => 'http://www.stadtbibliothek-rudolstadt.de ',
            'email' => 'stadtbibliothek@rudolstadt.de',
        ],
        2 => [
            'uid' => '3',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'name' => 'Lutherkirche',
            'street' => 'Caspar-Schulte-Straße',
            'district' => '',
            'city' => 'Rudolstadt',
            'zip' => '07407',
            'phone' => '03672 - 48 96 13',
            'web' => '',
            'email' => '',
        ],
    ],
    'tx_events_domain_model_event' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'title' => 'Allerlei Weihnachtliches (Heute mit Johannes Geißer)',
            'subtitle' => '',
            'global_id' => 'e_100347853',
            'highlight' => '0',
            'teaser' => '',
            'categories' => '0',
        ],
        1 => [
            'uid' => '2',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'title' => 'Tüftlerzeit',
            'subtitle' => '',
            'global_id' => 'e_100354481',
            'highlight' => '0',
            'teaser' => '',
            'categories' => '0',
        ],
        2 => [
            'uid' => '3',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'title' => 'Adventliche Orgelmusik (Orgel: KMD Frank Bettenhausen)',
            'subtitle' => '',
            'global_id' => 'e_100350503',
            'highlight' => '0',
            'teaser' => '',
            'categories' => '0',
        ],
    ],
];
