<?php

return [
    'sys_file' => [
        [
            'uid' => 1,
            'pid' => 0,
            'missing' => 0,
            'storage' => 1,
            'type' => \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE,
            'identifier' => '/staedte/beispielstadt/events/theater-rudolstadt_johannes-gei-er_photo-by-lisa-stern_web_-jpg.jpg',
            'extension' => 'jpg',
            'name' => 'theater-rudolstadt_johannes-gei-er_photo-by-lisa-stern_web_-jpg.jpg',
        ],
        [
            'uid' => 2,
            'pid' => 0,
            'missing' => 0,
            'storage' => 1,
            'type' => \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE,
            'identifier' => '/staedte/beispielstadt/events/tueftlerzeit-sfz-rudolstadt-jpg.jpg',
            'extension' => 'jpg',
            'name' => 'tueftlerzeit-sfz-rudolstadt-jpg.jpg',
        ],
        [
            'uid' => 3,
            'pid' => 0,
            'missing' => 0,
            'storage' => 1,
            'type' => \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE,
            'identifier' => '/staedte/beispielstadt/events/lutherkirche-jpg.jpg',
            'extension' => 'jpg',
            'name' => 'lutherkirche-jpg.jpg',
        ],
    ],
    'sys_file_reference' => [
        [
            'uid' => 1,
            'pid' => 2,
            'uid_local' => 1,
            'uid_foreign' => 1,
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'images',
            'sorting_foreign' => 1,
            'table_local' => 'sys_file',
            'title' => null,
            'description' => null,
            'alternative' => null,
        ],
        [
            'uid' => 2,
            'pid' => 2,
            'uid_local' => 2,
            'uid_foreign' => 2,
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'images',
            'sorting_foreign' => 1,
            'table_local' => 'sys_file',
            'title' => null,
            'description' => null,
            'alternative' => null,
        ],
        [
            'uid' => 3,
            'pid' => 2,
            'uid_local' => 3,
            'uid_foreign' => 3,
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'images',
            'sorting_foreign' => 1,
            'table_local' => 'sys_file',
            'title' => null,
            'description' => null,
            'alternative' => null,
        ],
    ],
    'sys_file_metadata' => [
        [
            'uid' => 1,
            'pid' => 0,
            'file' => 1,
            'title' => 'Theater-Rudolstadt_Johannes-Geißer_photo-by-Lisa-Stern_web_.jpg',
            'description' => '',
            'alternative' => '',
            'creator_tool' => 'destination.one',
            'source' => 'https://dam.destination.one/849917/279ac45b3fc701a7197131f627164fffd9f8cc77bc75165e2fc2b864ed606920/theater-rudolstadt_johannes-gei-er_photo-by-lisa-stern_web_-jpg.jpg',
            'copyright' => 'Max Mustermann',
        ],
        [
            'uid' => 2,
            'pid' => 0,
            'file' => 2,
            'title' => 'Tueftlerzeit©SFZ-Rudolstadt.jpg',
            'description' => 'Description of Tueftlerzeit',
            'alternative' => 'Description of Tueftlerzeit',
            'creator_tool' => 'destination.one',
            'source' => 'https://dam.destination.one/828118/f13bbf5602ffc406ebae2faa3527654dea84194666bce4925a1ca8bd3f50c5e9/tueftlerzeit-sfz-rudolstadt-jpg.jpg',
            'copyright' => '',
        ],
        [
            'uid' => 3,
            'pid' => 0,
            'file' => 3,
            'title' => 'Lutherkirche.jpg',
            'description' => '',
            'alternative' => '',
            'creator_tool' => 'destination.one',
            'source' => 'https://dam.destination.one/853436/109ac1cf87913e21b5e2b0ef0cc63d223a14374364952a855746a8e7c3fcfc36/lutherkirche-jpg.jpg',
            'copyright' => '',
        ],
    ],
];
