<?php

declare(strict_types=1);

return  [
    'tx_events_domain_model_organizer' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'name' => 'Schillerhaus Rudolstadt',
            'street' => 'Schillerstraße 25',
            'district' => '',
            'city' => 'Rudolstadt',
            'zip' => '07407',
            'phone' => '+ 49 3672 / 486470',
            'web' => 'http://schillerhaus.rudolstadt.de',
            'email' => 'schillerhaus@rudolstadt.de',
        ],
    ],
    'tx_events_domain_model_event' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'deleted' => '0',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            't3ver_stage' => '0',
            'title' => 'Allerlei Weihnachtliches (Heute mit Johannes Geißer)',
            'subtitle' => '',
            'global_id' => 'e_100347853',
            'highlight' => '0',
            'teaser' => '',
            'dates' => '1',
        ],
    ],
    'tx_events_domain_model_date' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '-1',
            'l10n_parent' => '0',
            't3ver_oid' => '0',
            't3ver_wsid' => '0',
            't3ver_state' => '0',
            'event' => '1',
            'start'  => (new DateTimeImmutable('Saturday 2099-12-19 15:00:00', new DateTimeZone('Europe/Berlin')))->getTimestamp(),
            'end'  => (new DateTimeImmutable('Saturday 2099-12-19 16:30:00', new DateTimeZone('Europe/Berlin')))->getTimestamp(),
            'canceled' => 'no',
            'postponed_date' => '0',
            'canceled_link' => '',
        ],
    ],
    'sys_category' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '0',
            'l10n_parent' => '0',
            'title' => 'Top Category',
            'items' => '0',
            'parent' => '0',
        ],
        1 => [
            'uid' => '2',
            'pid' => '2',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '0',
            'l10n_parent' => '0',
            'title' => 'Event Category Parent',
            'items' => '0',
            'parent' => '1',
        ],
        2 => [
            'uid' => '3',
            'pid' => '2',
            'hidden' => '0',
            'starttime' => '0',
            'endtime' => '0',
            'sys_language_uid' => '0',
            'l10n_parent' => '0',
            'title' => 'Weihnachten',
            'items' => '0',
            'parent' => '2',
        ],
    ],
    'sys_category_record_mm' => [
        0 => [
            'uid_local' => '3',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'categories',
        ],
    ],
    'sys_file_metadata' => [
        0 => [
            'uid' => '1',
            'pid' => '0',
            'title' => 'This title is longer then the supported 255 chars as limited by default by TYPO3 database. Also c …',
            'description' => 'This is a supported description',
            'alternative' => 'This is a supported description',
        ],
    ],
    'sys_file_reference' => [
        0 => [
            'uid' => '1',
            'uid_local' => '1',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'images',
        ],
    ],
];
