<?php

declare(strict_types=1);

return  [
    'tx_events_domain_model_event' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'features' => '6',
        ],
        1 => [
            'uid' => '2',
            'pid' => '2',
            'features' => '4',
        ],
        2 => [
            'uid' => '3',
            'pid' => '2',
            'features' => '0',
        ],
    ],
    'sys_category' => [
        0 => [
            'uid' => '1',
            'pid' => '2',
            'title' => 'Top Category',
            'parent' => '0',
            'hidden' => '0',
        ],
        1 => [
            'uid' => '2',
            'pid' => '2',
            'title' => 'Event Category Parent',
            'parent' => '1',
            'hidden' => '0',
        ],
        2 => [
            'uid' => '4',
            'pid' => '2',
            'title' => 'Event Feature Parent',
            'parent' => '1',
            'hidden' => '0',
        ],
        3 => [
            'uid' => '5',
            'pid' => '3',
            'title' => 'vorhandenes Feature',
            'parent' => '4',
            'hidden' => '1',
        ],
        4 => [
            'uid' => '6',
            'pid' => '3',
            'title' => 'Barrierefrei',
            'parent' => '4',
            'hidden' => '1',
        ],
        5 => [
            'uid' => '7',
            'pid' => '3',
            'title' => 'Zielgruppe Jugendliche',
            'parent' => '4',
            'hidden' => '1',
        ],
        6 => [
            'uid' => '8',
            'pid' => '3',
            'title' => 'Karten an der Abendkasse',
            'parent' => '4',
            'hidden' => '1',
        ],
        7 => [
            'uid' => '9',
            'pid' => '3',
            'title' => 'Ausreichende Lüftung',
            'parent' => '4',
            'hidden' => '1',
        ],
        8 => [
            'uid' => '10',
            'pid' => '3',
            'title' => 'Beachtung der Hygienehinweise',
            'parent' => '4',
            'hidden' => '1',
        ],
        9 => [
            'uid' => '11',
            'pid' => '3',
            'title' => 'neues Feature',
            'parent' => '4',
            'hidden' => '1',
        ],
    ],
    'sys_category_record_mm' => [
        0 => [
            'uid_local' => '5',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '1',
        ],
        1 => [
            'uid_local' => '6',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '2',
        ],
        2 => [
            'uid_local' => '7',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '3',
        ],
        3 => [
            'uid_local' => '8',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '4',
        ],
        4 => [
            'uid_local' => '9',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '5',
        ],
        5 => [
            'uid_local' => '10',
            'uid_foreign' => '1',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '6',
        ],
        6 => [
            'uid_local' => '5',
            'uid_foreign' => '2',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '1',
        ],
        7 => [
            'uid_local' => '6',
            'uid_foreign' => '2',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '2',
        ],
        8 => [
            'uid_local' => '7',
            'uid_foreign' => '2',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '3',
        ],
        9 => [
            'uid_local' => '11',
            'uid_foreign' => '2',
            'tablenames' => 'tx_events_domain_model_event',
            'fieldname' => 'features',
            'sorting' => '0',
            'sorting_foreign' => '4',
        ],
    ],
];
