routeEnhancers:
  EventsDateShow:
    type: Extbase
    extension: Events
    plugin: DateShow
    defaultController: 'Date::show'
    routes:
      -
        routePath: '/{date}'
        _controller: 'Date::show'
    aspects:
      date:
        type: PersistedAliasMapper
        tableName: tx_events_domain_model_date
        routeFieldName: slug
  EventsPagination:
    type: Plugin
    namespace: 'events_search'
    routePath: '/{localizedPage}-{currentPage}'
    aspects:
      localizedPage:
        type: LocaleModifier
        default: 'page'
        localeMap:
          - locale: 'de*'
            value: 'seite'
